changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: New features
      labels:
        - enhancement
    - title: Fixes and reliability
      labels:
        - bug
        - reliability
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
